dbt_framework:
  outputs:
    dev:
      account: BQB96235-EY_UK_PARTNER
      database: CHAUCER
      password: Snowflakeey@2025
      role: ACCOUNTADMIN
      schema: TEST_FRAMEWORK
      threads: 4
      type: snowflake
      user: PAVANSAI
      warehouse: COMPUTE_WH
  target: dev
dbt_project:
  outputs:
    dev:
      account: BQB96235-EY_UK_PARTNER
      database: DBT_PROJECT_DEV
      password: Snowflakeey@2025
      role: ACCOUNTADMIN
      schema: BRONZE
      threads: 1
      type: snowflake
      user: PAVANSAI
      warehouse: COMPUTE_WH
    prod:
      account: BQB96235-EY_UK_PARTNER
      database: DBT_PROJECT_PROD
      password: Snowflakeey@2025
      role: ACCOUNTADMIN
      schema: BRONZE
      threads: 1
      type: snowflake
      user: PAVANSAI
      warehouse: COMPUTE_WH      
  target: dev
