sources:
  - name: source
    database: dbt_project_dev  
    schema: source  
    tables:
      - name: dim_customer
      - name: dim_date
      - name: dim_product
      - name: dim_store
      - name: fact_sales
      - name: fact_returns
      - name: sampledata
      - name: sampledata_2
      - name: product_items