sources:
  - name: source
    database: '{{ target.database }}'
    schema: source  
    tables:
      - name: dim_customer
      - name: dim_date
      - name: dim_product
      - name: dim_store
      - name: fact_sales
      - name: fact_returns
      - name: sampledata
      - name: sampledata_2
      - name: product_items
  - name: landing
    database: '{{ target.database }}'
    schema: landing  
    tables:
      - name: landing_sales
      - name: landing_sales_inferschema
      - name: landing_orders
      - name: customers
      - name: customers_v2
  - name: raw
    database: '{{ target.database }}'       
    schema: raw  
    tables:
      - name: raw_sales       
  - name: config
    database: '{{ target.database }}'       
    schema: config  
    tables:
      - name: dq_rules    
  - name: config
    database: '{{ target.database }}'       
    schema: config  
    tables:
      - name: dq_rules_v2            
        